-- MySQL Script generated by MySQL Workbench
-- Sun Jul  4 19:54:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema totalizator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema totalizator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `totalizator` DEFAULT CHARACTER SET utf8 ;
USE `totalizator` ;

-- -----------------------------------------------------
-- Table `totalizator`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `role` ENUM('ADMIN', 'BOOKMAKER', 'CLIENT') NOT NULL DEFAULT 'CLIENT',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`sport_kinds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`sport_kinds` (
  `kind_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kind_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kind_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`events` (
  `event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sport_kind_id` INT UNSIGNED NOT NULL,
  `event_name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `event_status` ENUM('ACTIVE', 'COMPLETED') NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `kind_id_idx` (`sport_kind_id` ASC) VISIBLE,
  CONSTRAINT `event_kind_id`
    FOREIGN KEY (`sport_kind_id`)
    REFERENCES `totalizator`.`sport_kinds` (`kind_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`bets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`bets` (
  `bet_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bet_type` ENUM('DRAW', 'WIN', 'EXACT_SCORE') NOT NULL,
  `money` DECIMAL(10,2) NOT NULL,
  `win_money` DECIMAL(10,2) NULL,
  `date` DATE NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `event_id` INT UNSIGNED NOT NULL,
  `event_member1_id` INT UNSIGNED NULL,
  `event_member2_id` INT UNSIGNED NULL,
  `event_member1_score` INT NULL,
  `event_member2_score` INT NULL,
  PRIMARY KEY (`bet_id`),
  INDEX `for_key_1_idx` (`user_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `totalizator`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bet_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `totalizator`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`event_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`event_members` (
  `member_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `member_name` VARCHAR(45) NOT NULL,
  `kind_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `kind_id_idx` (`kind_id` ASC) VISIBLE,
  CONSTRAINT `member_kind_id`
    FOREIGN KEY (`kind_id`)
    REFERENCES `totalizator`.`sport_kinds` (`kind_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`event_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`event_results` (
  `event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `winner_id` INT UNSIGNED NOT NULL,
  `loser_id` INT UNSIGNED NOT NULL,
  `winner_score` INT NOT NULL,
  `loser_score` INT NOT NULL,
  PRIMARY KEY (`event_id`),
  CONSTRAINT `result_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `totalizator`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`event_link_eventmember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`event_link_eventmember` (
  `event_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `member_id_idx` (`member_id` ASC) VISIBLE,
  PRIMARY KEY (`event_id`, `member_id`),
  CONSTRAINT `link_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `totalizator`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `link_member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `totalizator`.`event_members` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`money_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`money_accounts` (
  `account_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `card_number` VARCHAR(45) NOT NULL,
  `balnce` DECIMAL(10,2) NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;
