-- MySQL Script generated by MySQL Workbench
-- Sun Jun 13 19:42:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema totalizator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema totalizator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `totalizator` DEFAULT CHARACTER SET utf8 ;
USE `totalizator` ;

-- -----------------------------------------------------
-- Table `totalizator`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `role` ENUM('ADMIN', 'BOOKMAKER', 'CLIENT') NOT NULL DEFAULT 'CLIENT',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`sport_kinds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`sport_kinds` (
  `kind_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kind_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kind_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`events` (
  `event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sport_kind_id` INT UNSIGNED NOT NULL,
  `event_name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `event_status` ENUM('ACTIVE', 'COMPLETED') NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `kind_id_idx` (`sport_kind_id` ASC) VISIBLE,
  CONSTRAINT `event_kind_id`
    FOREIGN KEY (`sport_kind_id`)
    REFERENCES `totalizator`.`sport_kinds` (`kind_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`event_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`event_members` (
  `member_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `member_name` VARCHAR(45) NOT NULL,
  `kind_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `kind_id_idx` (`kind_id` ASC) VISIBLE,
  CONSTRAINT `member_kind_id`
    FOREIGN KEY (`kind_id`)
    REFERENCES `totalizator`.`sport_kinds` (`kind_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`bets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`bets` (
  `bet_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bet_type` ENUM('DRAW', 'LOSS', 'WIN', 'EXACT_SCORE') NOT NULL,
  `money` DECIMAL(10,2) NOT NULL,
  `win_money` DECIMAL(10,2) NOT NULL,
  `date` DATE NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `event_id` INT UNSIGNED NOT NULL,
  `event_member1_id` INT UNSIGNED NOT NULL,
  `event_member2_id` INT UNSIGNED NOT NULL,
  `event_member1_score` INT NULL,
  `event_member2_score` INT NULL,
  PRIMARY KEY (`bet_id`),
  INDEX `for_key_1_idx` (`user_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `event_member1_id_idx` (`event_member1_id` ASC) VISIBLE,
  INDEX `event_member2_id_idx` (`event_member2_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `totalizator`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bet_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `totalizator`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `event_member1_id`
    FOREIGN KEY (`event_member1_id`)
    REFERENCES `totalizator`.`event_members` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `event_member2_id`
    FOREIGN KEY (`event_member2_id`)
    REFERENCES `totalizator`.`event_members` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`event_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`event_results` (
  `event_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `winner_id` INT UNSIGNED NOT NULL,
  `loser_id` INT UNSIGNED NOT NULL,
  `winner_score` INT NOT NULL,
  `loser_score` INT NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `winner_id_idx` (`winner_id` ASC) VISIBLE,
  INDEX `loser_id_idx` (`loser_id` ASC) VISIBLE,
  CONSTRAINT `result_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `totalizator`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `winner_id`
    FOREIGN KEY (`winner_id`)
    REFERENCES `totalizator`.`event_members` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `loser_id`
    FOREIGN KEY (`loser_id`)
    REFERENCES `totalizator`.`event_members` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totalizator`.`event_link_eventmember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totalizator`.`event_link_eventmember` (
  `event_id` INT UNSIGNED NOT NULL,
  `member_id` INT UNSIGNED NOT NULL,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `member_id_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `link_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `totalizator`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `link_member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `totalizator`.`event_members` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
